// Generated by CoffeeScript 1.3.3
(function() {
  var $, a1, a2, animatePetal, petalTransform, start, stripSerifu, talk, updateShareURL;

  $ = jQuery;

  jQuery.event.add(window, "load", function() {
    var text;
    $("#aiko").css("visibility", "visible");
    text = decodeURIComponent(location.search.substring(1));
    if (text.length > 0) {
      return talk(text);
    } else {
      return start();
    }
  });

  start = function() {
    $("#serifu").css({
      top: "640px"
    });
    $(".face").not("#face0").css("opacity", "0.0");
    return $("#face1").animate({
      opacity: "1.0"
    }, 1000).promise().then(function() {
      return $.when($("#face2").animate({
        opacity: "1.0"
      }, 400), $("#serifu").animate({
        top: "448px"
      }, 200));
    });
  };

  a1 = function() {
    return $("#arrow").animate({
      right: "20px",
      bottom: "20px"
    }, 300, a2);
  };

  a2 = function() {
    return $("#arrow").animate({
      right: "16px",
      bottom: "16px"
    }, 300, a1);
  };

  a1();

  animatePetal = function(element, duration) {
    var anim, obj, r;
    r = $(element).parent().width();
    obj = {
      angle: 0
    };
    anim = $.Animation(obj, {
      angle: Math.PI * 0.6
    }, {
      duration: duration
    });
    anim.progress(function() {
      var angle, transform, x, y;
      angle = obj.angle;
      x = Math.cos(angle) * r;
      y = Math.sin(angle) * r;
      transform = petalTransform(angle);
      return $(element).css({
        position: "absolute",
        left: x + 'px',
        top: y + 'px',
        transform: transform
      });
    });
    return anim;
  };

  petalTransform = function(angle) {
    var a;
    a = angle + Math.PI * -0.5;
    return 'rotate(' + a + 'rad)';
  };

  talk = function(text) {
    $("#text").text(text);
    $("#input").val(text);
    start();
    document.title = "藍子「" + stripSerifu(text) + "」";
    history.replaceState(null, null, "?" + encodeURIComponent(text));
    return updateShareURL();
  };

  stripSerifu = function(s) {
    var len;
    len = 4;
    if (s.length <= len) {
      return s;
    } else {
      return s.substring(0, len) + "…";
    }
  };

  updateShareURL = function() {
    var url;
    url = "https://twitter.com/share?" + $.param({
      url: location.href,
      text: document.title
    });
    return $("#twitter").prop("href", url);
  };

  $("#form").submit(function() {
    var text;
    text = $("#input").val();
    talk(text);
    return false;
  });

}).call(this);
